FROM golang:1.24-alpine as base
WORKDIR /build
RUN apk --update --no-cache add git gcc musl-dev libpcap-dev
COPY go.mod .
COPY go.sum .
RUN go mod download

FROM base as builder
WORKDIR /build
COPY . .
RUN go build -ldflags '-extldflags=-static' 

FROM alpine:3.22

COPY entrypoint.sh /
COPY --from=builder /build/dtap /usr/bin/dtap

ENTRYPOINT [ "/usr/bin/dtap" ]
