name: "Go check"

on:
  push:
    branches:
      - main
      - v2
  pull_request:
    branches:
      - main
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt update && sudo apt install -y libpcap-dev
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Test
      run: |
        go install github.com/onsi/ginkgo/v2/ginkgo
        ginkgo run --label-filter='!privileged' ./...