name: "config schema check"

on:
  push:
    branches:
      - main
      - v2
  pull_request:
    branches:
      - main
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn global add ajv-cli
    - run: make schema
